[deps]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NeuralOperators = "ea5c82af-86e5-48da-8ee1-382d6ad7af4b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
