name = "FourierNeuralOperators"
uuid = "fad0b1a5-a77e-47d0-848c-9f04c700d34f"
authors = ["AzamatB"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
AbstractFFTs = "1.5.0"
Static = "1.3.1"

[extras]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReTest"]
